FROM n8nio/n8n:latest

ENV NODE_ENV=production
ENV N8N_HOST=${RENDER_EXTERNAL_HOSTNAME}
ENV N8N_PORT=${PORT}
ENV N8N_PROTOCOL=https
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false

EXPOSE ${PORT}

CMD ["n8n", "start"]
